In [2]:
import pandas as pd

In [22]:
df_remap = pd.read_csv('../../pretrain_data/pistachio_reaction_condition_identify.csv')

In [23]:
df_remap

,_ID,canonical_rxn,catalyst,solvent,reagent,temperature
0,US07939546B2,Cc1cc(Nc2ccc(NC(=O)c3ccc([N+](=O)[O-])cc3)cn2)...,[Pd],C1CCOC1,NaN,25.0
1,US08058299B2,CC(C)(C)OC(=O)N1CCC(c2ccc(NC(=O)c3nc(-c4ccccc4...,NaN,ClCCl,NaN,25.0
2,US08546427B2,CC1(C)CC(c2ccccc2N)Nc2ccc(Cl)cc21.O=S(=O)(Cl)c...,NaN,ClCCl,c1ccncc1,25.0
3,US08796294B2,Cc1cccc(C)c1N.O=C(O)c1ccc(Nc2nc(-c3ccc4[nH]ccc...,NaN,CC(=O)N(C)C,CCN(C(C)C)C(C)C,25.0
4,US07253158B2,COC(=O)C1(c2ccc(CN([C@@H]3CCCCNC3=O)S(=O)(=O)c...,NaN,CO,[Na+].[OH-],25.0
...,...,...,...,...,...,...
266241,US08829193B2,CC(C)(C)OC(=O)N[C@H]1CN(c2ccncc2[N+](=O)[O-])C...,NaN,CCO,NaN,25.0
266242,US08846741B2,Cn1cnc(S(=O)(=O)NCCOc2ccc3c(c2)[C@H](Cc2ccccc2...,NaN,C1CCOC1,CO,25.0
266243,US08618289B2,COc1cc2ncnc(Cl)c2cc1OCCCCl.Nc1cccc(S)c1>>COc1c...,NaN,C1CCOC1,[H-].[Na+],25.0
266244,US08415333B2,N#Cc1ccc(C2=CCOCC2)cc1>>N#Cc1ccc(C2CCOCC2)cc1,[Pd],CCO,NaN,25.0
266245,US07700591B2,CC(C)(C)Oc1ccc(C(F)(F)F)cc1CN.Cc1ccc(C)n1C1C=C...,NaN,CCOC(C)=O,CCN(C(C)C)C(C)C,25.0

In [24]:
df_remap['temperature'].value_counts()

 25.0     219197
 0.0       19377
-78.0       2433
 50.0       2256
 60.0       2055
 5.0        1842
 80.0       1774
 40.0       1599
 100.0      1278
 20.0       1240
 10.0       1151
 70.0       1115
 90.0        797
 30.0        797
-10.0        651
-20.0        562
 65.0        495
 45.0        476
 23.0        435
 55.0        429
 120.0       422
 110.0       413
 15.0        388
 35.0        382
 75.0        337
 85.0        319
-5.0         310
-70.0        278
 150.0       260
-40.0        259
 130.0       258
-15.0        240
 95.0        230
 4.0         222
-30.0        219
 140.0       205
 22.0        167
 160.0       117
-60.0        117
-50.0        111
 200.0       110
 180.0       106
 105.0        84
 115.0        79
 125.0        75
 3.0          64
-25.0         63
 78.0         60
-65.0         56
 170.0        55
 2.0          53
 250.0        51
 8.0          47
-75.0         46
 135.0        44
 28.0         40
Name: temperature, dtype: int64

In [21]:
positive

0        c1c(Nc2c3c(sc4c3CCNC4)ncn2)cc(c(c1)F)Cl.C(OP(C...
1        C(C)OP(OCC)(=O)CC(=O)O.O(CCOCCOC)C.c1(C)ccc(S(...
2        Fc1c(cc(cc1)Nc1ncnc2c1c1c(s2)CNCC1)Cl.CCOP(CC(...
3        n1cnc2sc3c(c2c1Nc1ccc(c(Cl)c1)F)CCNC3.P(OCC)(=...
4        c1cc(Cl)c(cc1)Cl.c1c(N(C)C)ccnc1.O=P(CC(=O)O)(...
                               ...
40800    OCC.[Pd].c1cc(ccc1C1CCOCC=1)C#N>>c1c(C#N)ccc(c...
40801    CN(C=O)C.[Cs+].Br[Cu].C1C=C(c2ccc(cc2)C#N)CCO1...
40802    C1C(=CCOC1)c1ccc(cc1)C#N.CC(=O)CC(C)C.[F-].[Cs...
40803    ClCCCl.c1c(ccc(C#N)c1)C1=CCOCC1.c1cc(ccc1)Cl.I...
40804    C1CC(=CCO1)c1ccc(C#N)cc1.C1CN2C(CCCCC2)=NC1.[A...
Name: positive_smi_1, Length: 40805, dtype: object

In [16]:
df_remap['temperature'].value_counts()

 25.0     219197
 0.0       19377
-78.0       2433
 50.0       2256
 60.0       2055
 5.0        1842
 80.0       1774
 40.0       1599
 100.0      1278
 20.0       1240
 10.0       1151
 70.0       1115
 90.0        797
 30.0        797
-10.0        651
-20.0        562
 65.0        495
 45.0        476
 23.0        435
 55.0        429
 120.0       422
 110.0       413
 15.0        388
 35.0        382
 75.0        337
 85.0        319
-5.0         310
-70.0        278
 150.0       260
-40.0        259
 130.0       258
-15.0        240
 95.0        230
 4.0         222
-30.0        219
 140.0       205
 22.0        167
 160.0       117
-60.0        117
-50.0        111
 200.0       110
 180.0       106
 105.0        84
 115.0        79
 125.0        75
 3.0          64
-25.0         63
 78.0         60
-65.0         56
 170.0        55
 2.0          53
 250.0        51
 8.0          47
-75.0         46
 135.0        44
 28.0         40
Name: temperature, dtype: int64

In [10]:
null_counts = df_remap.isna().sum()
print(null_counts)

source                0
canonical_rxn         0
catalyst1        231899
solvent1           2845
solvent2         218855
reagent1          74635
reagent2         206607
temperature           0
dataset               0
dtype: int64

In [15]:
df_remap = df_remap.drop(columns=['solvent2', 'reagent2','dataset'])

# Save the modified DataFrame to a new CSV file
df_remap.to_csv('pistachio_reaction_condition_identify.csv', index=False)

In [16]:
df_rxn_yield = pd.read_csv('predicted_yields.csv')

In [17]:
df_rxn_yield = df_rxn_yield.rename(columns={'rxn_smiles': 'canonical_rxn'})

In [18]:
df_rxn_yield

                                            canonical_rxn  predicted_yield
0       O=C(CCl)N1CCN(c2ccc(Cl)cc2)CC1.c1ccc2[nH]cnc2c...        83.065588
1       Cc1c[nH]c(C)n1.O=C(CCl)N1CCN(c2ccc(Cl)cc2)CC1>...        80.075804
2       CSc1n[nH]c(N)n1.O=C(CCl)N1CCN(c2ccc(Cl)cc2)CC1...        73.606949
3       Brc1ccccc1-c1nnn[nH]1.O=C(CCl)N1CCN(c2ccc(Cl)c...        72.065263
4       CC#N.COC(=O)C(Br)c1cccc(OC)c1.Cc1n[nH]c(C(F)(F...        72.226152
...                                                   ...              ...
296353  CSc1ccc(B(O)O)cc1.O=c1[nH]ccc2c(Br)cccc12>>CSc...        73.556050
296354   COc1ccc2c(c1)C(=O)CC2.NO>>COc1ccc2c(c1)C(=O)NCC2        80.297546
296355  COC(=O)c1c[nH]c(=O)c2ccccc12>>O=C(O)c1c[nH]c(=...        77.294984
296356  NC1CC1.O=C(O)c1c[nH]c(=O)c2ccccc12>>O=C1NCC(C(...        70.296990
296357  FC(F)(F)Sc1ccc(CBr)cc1.O=C1NCCc2c(O)cccc21>>O=...        57.187090

[296358 rows x 2 columns]

In [19]:
df1 = pd.read_csv("../USPTO_yield/gram_trn_random_split.csv")
df2= pd.read_csv("../USPTO_yield/gram_val_random_split.csv")
df3 = pd.read_csv("../USPTO_yield/milligram_trn_random_split.csv")
df4 = pd.read_csv("../USPTO_yield/milligram_val_random_split.csv")

In [20]:
com_df = pd.concat([df1, df2, df3,df4])

In [21]:
com_df

                                                    text  labels
0      CCOCC.C[C@@](C#N)(N[C@@H](CO)c1ccccc1)C(F)(F)F...   0.866
1      CN(C)C=O.COc1cc(CBr)cc(OC)c1OC.O=C([O-])[O-]~[...   0.687
2      CN(C)C=O.Cc1[nH]cc(CCC(=O)O)c1S(=O)(=O)c1ccccc...   0.674
3      CC(C)(C)[O-]~[Na+].COCCOC.Nc1nc(Cl)nc2c1ncn2C1...   0.520
4      CC(C)(C)NNC(=O)c1ccccc1.ClCCl.O=C(Cl)c1ccc(Cl)...   0.778
...                                                  ...     ...
24158  Cc1cc(C)nc(C)c1.F[B-](F)(F)F~O=[N+]=O.O=C1N[C@...   0.209
24159  C1CCOC1.COc1ccc(S(=O)(=O)Cl)cc1N1CCN(C(=O)C(Cl...   0.374
24160  C1CCOC1.C1CCOC1~Cc1ccc([Mg]Br)cc1.C1CCOC1~[Cl-...   0.246
24161  C1CCOC1~ClCCCl.CC(=O)O[BH-](OC(C)=O)OC(C)=O~[N...   0.342
24162  CCOC(=O)c1ncc2c(C3=CCCCC3)noc2c1O.CCOC(C)=O.CC...   0.759

[399727 rows x 2 columns]

In [22]:
com_df = com_df.rename(columns={'text': 'canonical_rxn', 'labels': 'yield'})

In [23]:
merged_df = pd.merge(df_remap, com_df, on='canonical_rxn', how='inner')

In [24]:
merged_df_1 = pd.merge(df_rxn_yield, com_df, on='canonical_rxn', how='inner')

In [25]:
merged_df_1

                                         canonical_rxn  predicted_yield  yield
0    O=C1Cc2ccccc2N1.O=S(=O)(O)Cl>>O=C1Cc2cc(S(=O)(...        71.519734  0.806
1    O=C1Cc2ccccc2N1.O=S(=O)(O)Cl>>O=C1Cc2cc(S(=O)(...        71.519734  0.806
2    O=C1Cc2ccccc2N1.O=S(=O)(O)Cl>>O=C1Cc2cc(S(=O)(...        71.519734  0.806
3    O=C1Cc2ccccc2N1.O=S(=O)(O)Cl>>O=C1Cc2cc(S(=O)(...        71.519734  0.806
4    O=C1Cc2ccccc2N1.O=S(=O)(O)Cl>>O=C1Cc2cc(S(=O)(...        71.519734  0.806
..                                                 ...              ...    ...
250  Nc1ccc(F)cc1.O=C1CCNC(=O)C1>>O=C1C=C(Nc2ccc(F)...        74.700160  0.942
251  CCOC=C(C(=O)OCC)C(=O)OCC.COc1ccc(Cn2nccc2N)cc1...        62.630283  0.630
252  Brc1ccc2c(c1)OCO2.C1CCOC1.CCOC(=O)C1CCN(C(=O)O...        76.196765  0.649
253  Clc1ccnc(Cl)c1.Nc1ccc(O)cc1F>>Nc1ccc(Oc2ccnc(C...        67.752213  0.854
254  CC(=O)Nc1cc(C2=NOC(c3cc(Cl)cc(Cl)c3)(C(F)(F)F)...        67.462647  0.593

[255 rows x 3 columns]

In [27]:
merged_df

,source,canonical_rxn,catalyst1,solvent1,solvent2,reagent1,reagent2,temperature,dataset,yield
0,US05492802,CC(=O)O.COC1CCC(OC)O1.Cc1nc2cc(N)ccc2o1.ClCCl>...,NaN,ClCCl,NaN,NaN,NaN,25.0,train,0.400
1,US08748421B2,C1COCCN1.Clc1nc(Cl)nc(Cl)n1>>Clc1nc(Cl)nc(N2CC...,NaN,ClCCl,NaN,CCN(CC)CC,NaN,78.0,train,0.283
2,US08575159B2,C1COCCN1.Clc1nc(Cl)nc(Cl)n1>>Clc1nc(Cl)nc(N2CC...,NaN,ClC(Cl)Cl,O,NaN,NaN,25.0,train,0.283
3,US05489591,C1COCCN1.Clc1nc(Cl)nc(Cl)n1>>Clc1nc(Cl)nc(N2CC...,NaN,COCCOC,NaN,NaN,NaN,-15.0,train,0.283
4,US08575159B2,C1COCCN1.Clc1nc(Cl)nc(Cl)n1>>Clc1nc(Cl)nc(N2CC...,NaN,ClCCl,NaN,CCN(CC)CC,NaN,-78.0,train,0.283
...,...,...,...,...,...,...,...,...,...,...
274,US04594441,CCO.O=C(NCCCCCCNC(=O)OC1CCCCC1)OC1CCCCC1>>CCOC...,NaN,CCO,NaN,NaN,NaN,25.0,train,0.922
275,US05665718,C=CCBr.CCN(C(C)C)C(C)C.CN(C)C=O.CN1Cc2c(-c3nc(...,NaN,CN(C)C=O,NaN,NaN,NaN,25.0,train,0.759
276,US06762224B2,C1CCOC1.CCCCCC(C)OC(=O)OC(=O)[O-].CN(C)c1ccncc...,CN(C)c1ccncc1,C1CCOC1,NaN,NaN,NaN,25.0,train,0.448
277,US07897771B2,C1COCCO1.CC(C)(C)OC(=O)N1CCc2nn(-c3cccc(F)c3)c...,NaN,C1COCCO1,NaN,NaN,NaN,25.0,train,0.346
278,US04154761,CCC(C)=O.CN(c1ccccc1)c1cccc(NCc2ccccc2)c1.O=C(...,NaN,CCC(C)=O,NaN,NaN,NaN,0.0,train,0.666

In [5]:
df = pd.read_csv('../../../dataset/pretrain_data/aug_pistachio_pretraining_train_dataset.csv')
reduced_df = df.iloc[:len(df)//2]

In [6]:
reduced_df.to_csv('test.csv',index=False)